- name: initialize database
  command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql{{ pg_version }}-setup initdb"
  args:
    creates: "/var/lib/pgsql/{{ postgres_version }}/initdb.log"
  notify:
    - start postgresql 
- name: create replication user
  postgresql_user:
    state: present
    name: "{{ postgres_replication_user }}"
    password: "{{ postgres_replication_user_pass }}"
    role_attr_flags: LOGIN,REPLICATION
